In [5]:
# Sequential的使用
import torch
import torchvision
from torch import nn
from torch.nn import Conv2d,MaxPool2d,Flatten,Linear,Sequential
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.module = Sequential(
            Conv2d(3,32, kernel_size=5,padding=2),
            Conv2d(32, 32, kernel_size=5,padding=2),
            MaxPool2d(2),
            MaxPool2d(2),
            Conv2d(32, 64, kernel_size=5,padding=2),
            MaxPool2d(2),
            Flatten(),
            Linear(1024,64),
            Linear(64,10)
        )
        
    def forward(self,x):
        x = self.module(x)
        return x
    
net = Net()
input = torch.ones((64,3,32,32))
output = net(input)

writer = SummaryWriter("./p1")
writer.add_graph(net,input)
writer.close()

In [3]:
# 损失函数和反向传播
from torch import nn
import torch

inputs = torch.tensor([1,2,3],dtype=torch.float32)
targets = torch.tensor([1,2,5],dtype=torch.float32)

inputs = torch.reshape(inputs,(1,1,1,3))
targets = torch.reshape(targets,(1,1,1,3))

loss = nn.L1Loss()
result = loss(inputs,targets)
print(result)

tensor(0.6667)


In [5]:
# Loss Function的使用
import torch
import torchvision
from torch import nn
from torch.nn import Conv2d,MaxPool2d,Flatten,Linear,Sequential
from torch.utils.tensorboard import SummaryWriter
from torch.utils.data import DataLoader

datasets = torchvision.datasets.CIFAR10(root='./data', train=False,transform=torchvision.transforms.ToTensor())
data_loader = DataLoader(datasets,batch_size=1)

class Net(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.module = Sequential(
            Conv2d(3,32, kernel_size=5,padding=2),
            Conv2d(32, 32, kernel_size=5,padding=2),
            MaxPool2d(2),
            MaxPool2d(2),
            Conv2d(32, 64, kernel_size=5,padding=2),
            MaxPool2d(2),
            Flatten(),
            Linear(1024,64),
            Linear(64,10)
        )
        
    def forward(self,x):
        x = self.module(x)
        return x
    
net = Net()

optimizer = torch.optim.SGD(net.parameters(),lr=0.001) 
cross_loss = nn.CrossEntropyLoss()
for data in data_loader:
    imgs,targets = data
    output = net(imgs)
    cross_loss(output,targets)
    print(output)
# writer = SummaryWriter("./p1")
# writer.add_graph(net,input)
# writer.close()

tensor([[ 0.1005, -0.0203, -0.1210, -0.0220,  0.0262,  0.1439, -0.1224,  0.1055,
          0.0791,  0.0950]], grad_fn=<AddmmBackward0>)
tensor([[ 0.1052, -0.0463, -0.1219, -0.0348,  0.0327,  0.1596, -0.1064,  0.0843,
          0.0731,  0.1254]], grad_fn=<AddmmBackward0>)
tensor([[ 0.1044, -0.0438, -0.1205, -0.0328,  0.0359,  0.1530, -0.1103,  0.0799,
          0.0549,  0.1131]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0974, -0.0446, -0.1214, -0.0363,  0.0377,  0.1476, -0.1140,  0.0868,
          0.0569,  0.1196]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0863, -0.0202, -0.1086, -0.0214,  0.0300,  0.1428, -0.1145,  0.1022,
          0.0727,  0.0862]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0951, -0.0180, -0.1120, -0.0308,  0.0241,  0.1441, -0.1135,  0.0902,
          0.0702,  0.1047]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0971, -0.0272, -0.0972, -0.0238,  0.0330,  0.1392, -0.0883,  0.0988,
          0.0519,  0.1006]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0906, -0.0301, -0.1004, -0.0278,  0.

In [2]:
# 优化器
import torch
import torchvision
from torch import nn
from torch.nn import Conv2d,MaxPool2d,Flatten,Linear,Sequential
from torch.utils.data import DataLoader

datasets = torchvision.datasets.CIFAR10(root='./data', train=False,transform=torchvision.transforms.ToTensor())
data_loader = DataLoader(datasets,batch_size=1)

class Net(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.module = Sequential(
            Conv2d(3,32, kernel_size=5,padding=2),
            Conv2d(32, 32, kernel_size=5,padding=2),
            MaxPool2d(2),
            MaxPool2d(2),
            Conv2d(32, 64, kernel_size=5,padding=2),
            MaxPool2d(2),
            Flatten(),
            Linear(1024,64),
            Linear(64,10)
        )
        
    def forward(self,x):
        x = self.module(x)
        return x
    
net = Net()
cross_loss = nn.CrossEntropyLoss()
optimism = torch.optim.SGD(net.parameters(),lr=0.01)
for epoch in range(20): #训练20抡
    running_loss = 0.0
    for data in data_loader:
        imgs,targets = data
        output = net(imgs)
        result_loss = cross_loss(output,targets)
        optimism.zero_grad()
        result_loss.backward()  #反向传播
        running_loss = running_loss + result_loss
    print(running_loss)

tensor(23052.9062, grad_fn=<AddBackward0>)


KeyboardInterrupt: 

In [ ]:
# 模型的保存和模型的加载
import torchvision

vgg16 = torchvision.models.vgg16(pretrained=False)
# 保存方式一  
torch.save(vgg16, "vgg16_method1.pth")
# 保存方式二 (官方推荐)
torch.save(vgg16.state_dict(), "vgg16_method2.pth")
# 加载保存方式二的模型
vgg16 = torchvision.models.vgg16(pretrained=False)
vgg16.load_state_dict(torch.load("vgg16_method2.pth"))
print(vgg16)

In [2]:
# 模型训练套路
import torchvision
from torch.utils.data import DataLoader
import torch.nn as nn
from torch.utils.tensorboard import SummaryWriter
import torch

learning_rate = 1e-3
writer = SummaryWriter("logs")
#准备数据集
train_data = torchvision.datasets.CIFAR10(root="./data",train=True,transform=torchvision.transforms.ToTensor())
test_data = torchvision.datasets.CIFAR10(root="./data",train=False,transform=torchvision.transforms.ToTensor())

# length长度
train_data_length = len(train_data)
test_data_length = len(test_data)
print("训练集的长度为{}，测试集的长度为{}".format(train_data_length,test_data_length))

# 使用DataLoader来加载数据
train_loader = DataLoader(train_data,batch_size=64)
test_loader = DataLoader(train_data,batch_size=64)

#建立神经网络
class Net(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.model = nn.Sequential(
            nn.Conv2d(3,32,5,1,2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,32,5,1,2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,64,5,1,2),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(64*16,64),
            nn.Linear(64,10),
        )
    def forward(self,x):
        x = self.model(x)
        return x
net = Net()
# 定义损失函数
loss_func = nn.CrossEntropyLoss()

#定义优化器
optimzer = torch.optim.SGD(net.parameters(),lr=learning_rate)

#设置训练网络的一些参数
total_train_step = 0
total_test_step = 0
#训练的轮数
epoch = 1
for i in range(1,epoch+1):
    print("第{}轮训练".format(i))
    
    #训练步骤开始
    net.train()
    for data in train_loader:
        imgs,targets = data
        output = net(imgs)
        # 损失值
        loss = loss_func(output,targets)
        # 优化调优
        optimzer.zero_grad()
        loss.backward()
        optimzer.step()
        total_train_step += 1
        if total_train_step % 100 == 0:
            print("训练次数: {},loss: {}".format(total_train_step,loss.item()))
            writer.add_scalar("train_loss",loss.item(),total_train_step)
    # 测试调优
    net.eval()
    total_test_loss = 0
    total_accuracy = 0
    with torch.no_grad():
        for data in test_loader:
            imgs,targets = data
            output = net(imgs)
            loss = loss_func(output,targets)
            total_test_loss += loss.item()
            accuracy = (output.argmax(1) == targets).sum()
            total_accuracy += accuracy
            
    print("整体上的损失值为Loss: {}".format(total_test_loss))
    print("整体上的测试准确率为Accuracy: {}".format(total_accuracy/test_data_length))
    writer.add_scalar("test_loss",total_test_loss,total_test_step)
    writer.add_scalar("test_accuracy", total_accuracy/test_data_length,total_test_step)
    total_test_step += 1
    
    torch.save(net,"richu_{}.pth".format(i))
    # torch.save(net.state_dict(),"richu_{}.pth".format(i))
    print("模型已保存")
    
writer.close()

训练集的长度为50000，测试集的长度为10000
第1轮训练
训练次数: 100,loss: 2.295380115509033
训练次数: 200,loss: 2.302664279937744
训练次数: 300,loss: 2.3085787296295166
训练次数: 400,loss: 2.2967424392700195
训练次数: 500,loss: 2.30216121673584
训练次数: 600,loss: 2.293686628341675
训练次数: 700,loss: 2.289689064025879
整体上的损失值为Loss: 1796.8302900791168
整体上的测试准确率为Accuracy: 0.5217000246047974
模型已保存


In [ ]:
# 使用GPU训练
# 模型训练套路
import torchvision
from torch.utils.data import DataLoader
import torch.nn as nn
from torch.utils.tensorboard import SummaryWriter
import torch

learning_rate = 1e-3
writer = SummaryWriter("logs")
#准备数据集
train_data = torchvision.datasets.CIFAR10(root="./data",train=True,transform=torchvision.transforms.ToTensor())
test_data = torchvision.datasets.CIFAR10(root="./data",train=False,transform=torchvision.transforms.ToTensor())

# length长度
train_data_length = len(train_data)
test_data_length = len(test_data)
print("训练集的长度为{}，测试集的长度为{}".format(train_data_length,test_data_length))

# 使用DataLoader来加载数据
train_loader = DataLoader(train_data,batch_size=64)
test_loader = DataLoader(train_data,batch_size=64)

#建立神经网络
class Net(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.model = nn.Sequential(
            nn.Conv2d(3,32,5,1,2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,32,5,1,2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,64,5,1,2),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(64*16,64),
            nn.Linear(64,10),
        )
    def forward(self,x):
        x = self.model(x)
        return x
net = Net()
net.cuda()
# 定义损失函数
loss_func = nn.CrossEntropyLoss()
loss_func = loss_func.cuda()
#定义优化器
optimzer = torch.optim.SGD(net.parameters(),lr=learning_rate)

#设置训练网络的一些参数
total_train_step = 0
total_test_step = 0
#训练的轮数
epoch = 1
for i in range(1,epoch+1):
    print("第{}轮训练".format(i))
    
    #训练步骤开始
    net.train()
    for data in train_loader:
        imgs,targets = data
        imgs = imgs.cuda()
        targets = targets.cuda()
        output = net(imgs)
        # 损失值
        loss = loss_func(output,targets)
        # 优化调优
        optimzer.zero_grad()
        loss.backward()
        optimzer.step()
        total_train_step += 1
        if total_train_step % 100 == 0:
            print("训练次数: {},loss: {}".format(total_train_step,loss.item()))
            writer.add_scalar("train_loss",loss.item(),total_train_step)
    # 测试调优
    net.eval()
    total_test_loss = 0
    total_accuracy = 0
    with torch.no_grad():
        for data in test_loader:
            imgs,targets = data
            imgs = imgs.cuda()
            targets = targets.cuda()
            output = net(imgs)
            loss = loss_func(output,targets)
            total_test_loss += loss.item()
            accuracy = (output.argmax(1) == targets).sum()
            total_accuracy += accuracy
            
    print("整体上的损失值为Loss: {}".format(total_test_loss.item()))
    print("整体上的测试准确率为Accuracy: {}".format(total_accuracy/test_data_length))
    writer.add_scalar("test_loss",total_test_loss,total_test_step)
    writer.add_scalar("test_accuracy", total_accuracy/test_data_length,total_test_step)
    total_test_step += 1
    
    torch.save(net,"richu_{}.pth".format(i))
    # torch.save(net.state_dict(),"richu_{}.pth".format(i))
    print("模型已保存")
    
writer.close()

In [ ]:
#.to(device)
# device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")